name: trainer_app
description: The Trainer application for trainers.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  hmssdk_flutter: ^1.11.0 # 100ms SDK
  hive_flutter: ^1.1.0
  shared:
    path: ../shared
  http: ^1.6.0
  intl: ^0.20.2
  firebase_core: ^3.15.2
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
