name: shared
description: Shared models, services, widgets, and utilities for Guru and Trainer apps.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^3.0.0 # Using a general lints package for Dart packages
